/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pertemuan9;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


public class Insert extends javax.swing.JDialog {

    Connection conn;
    Statement stmt;


    public Insert(Tampilan parent, boolean modal) {
        super(parent, modal);
        initComponents();
        connect();
    }

    // method koneksi ke database
    public void connect() {
        try {
            // Load driver PostgreSQL
            Class.forName("org.postgresql.Driver");

            // URL database PostgreSQL
            String URL = "jdbc:postgresql://localhost:5432/PBO4";
            String USER = "postgres";
            String PASSWORD = "BISMILLAH";

            conn = DriverManager.getConnection(URL, USER, PASSWORD);
            stmt = conn.createStatement();

        } catch (Exception e) {
            e.printStackTrace(); // cukup print error di console
        }
    }
    public void bersih() {
        textidkue.setText("");
        textnamakue.setText("");
        textharga.setText("");
        textstock.setText("");
    }

    private void tambahData() {
        try {
            if (textidkue.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Isi ID Roti !");
            } else if (textnamakue.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Isi Nama Roti !");
            } else if (textharga.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Isi Harga !");
            } else if (textstock.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Isi Stock !");
            } else {
                String sql = "INSERT INTO tokoroti (id_kue, nama_kue, harga, stock) VALUES (?, ?, ?, ?)";
                PreparedStatement pst = conn.prepareStatement(sql);

                pst.setString(1, textidkue.getText());
                pst.setString(2, textnamakue.getText());
                pst.setInt(3, Integer.parseInt(textharga.getText()));
                pst.setInt(4, Integer.parseInt(textstock.getText()));

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");

                // Kosongkan input
                textidkue.setText("");
                textnamakue.setText("");
                textharga.setText("");
                textstock.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Simpan gagal: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textidkue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textnamakue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textharga = new javax.swing.JTextField();
        textstock = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonSIMPAN = new javax.swing.JButton();
        jButtonBATAL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        textidkue.setBackground(new java.awt.Color(255, 255, 255));
        textidkue.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Id Roti");

        jLabel2.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nama Roti");

        textnamakue.setBackground(new java.awt.Color(255, 255, 255));
        textnamakue.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Harga");

        textharga.setBackground(new java.awt.Color(255, 255, 255));
        textharga.setForeground(new java.awt.Color(0, 0, 0));
        textharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texthargaActionPerformed(evt);
            }
        });

        textstock.setBackground(new java.awt.Color(255, 255, 255));
        textstock.setForeground(new java.awt.Color(0, 0, 0));
        textstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textstockActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Stok");

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(23, 71, 115));
        jLabel5.setText("TAMBAH DATA ROTI");

        jButtonSIMPAN.setBackground(new java.awt.Color(37, 81, 125));
        jButtonSIMPAN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSIMPAN.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSIMPAN.setText("SIMPAN");
        jButtonSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSIMPANActionPerformed(evt);
            }
        });

        jButtonBATAL.setBackground(new java.awt.Color(37, 81, 125));
        jButtonBATAL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBATAL.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBATAL.setText("BATAL");
        jButtonBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBATALActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBATAL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSIMPAN))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textstock, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textharga, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textidkue, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textnamakue, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textidkue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textnamakue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textharga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textstock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSIMPAN)
                    .addComponent(jButtonBATAL))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texthargaActionPerformed

    private void textstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textstockActionPerformed

    private void jButtonSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSIMPANActionPerformed
        try {
            String sql = "INSERT INTO tokoroti (id_kue, nama_kue, harga, stock) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, textidkue.getText());
            pst.setString(2, textnamakue.getText());
            pst.setInt(3, Integer.parseInt(textharga.getText()));
            pst.setInt(4, Integer.parseInt(textstock.getText()));
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");

            bersih();
            dispose();
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Simpan gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSIMPANActionPerformed

    private void jButtonBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBATALActionPerformed
       bersih();
    }//GEN-LAST:event_jButtonBATALActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Insert dialog = new Insert(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBATAL;
    private javax.swing.JButton jButtonSIMPAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textharga;
    private javax.swing.JTextField textidkue;
    private javax.swing.JTextField textnamakue;
    private javax.swing.JTextField textstock;
    // End of variables declaration//GEN-END:variables
}
